"""业务字段英文 → 中文映射表（数据源：Domain / VO / Param 文档）。"""

FIELD_TRANSLATIONS: list[tuple[str, str]] = [
    # 一、通用字段 BaseDomain
    ("id", "主键id"),
    ("createdAt", "创建时间"),
    ("updatedAt", "更新时间"),
    # 2.1 LarkProjectWorkItem
    ("workItemId", "工作项ID"),
    ("name", "名称"),
    ("workItemTypeKey", "工作项类型"),
    ("projectKey", "空间标识"),
    ("projectName", "空间名称"),
    ("workItemStatus", "工作项状态"),
    ("workItemType", "项目类型"),
    ("status", "项目冻结状态"),
    ("isBusinessProject", "是否商业项目"),
    ("projectEntity", "项目所属主体"),
    ("series", "所属系列"),
    ("level", "项目评级"),
    ("clientName", "客户名称"),
    ("startTime", "开始时间"),
    ("firstPlanTime", "首次排期时间"),
    ("publicTime", "发布时间"),
    ("workDays", "项目天数"),
    ("delay", "是否延期"),
    ("delayTimes", "延期次数"),
    ("delayDays", "延期天数"),
    ("revenue", "营收"),
    ("remark", "备注"),
    ("grossProfit", "预计毛利"),
    ("grossProfitRate", "预计毛利率"),
    ("netProfit", "预计税前净利润"),
    ("netProfitRate", "预计税前净利润率"),
    ("actualGrossProfit", "最终毛利"),
    ("actualGrossProfitRate", "最终毛利率"),
    ("actualNetProfit", "实际税前净利润"),
    ("actualNetProfitRate", "实际税前净利润率"),
    ("expectPersonNum", "预计人员数量"),
    ("actualPersonNum", "实际人员数量"),
    ("expectTotalDays", "预计总天数"),
    ("actualTotalDays", "实际总天数"),
    ("expectTotalPersonDay", "预计人日"),
    ("actualTotalPersonDay", "最终人日"),
    ("expectPersonCost", "预期人日成本"),
    ("actualPersonCost", "动态人日成本"),
    ("budget", "外部支出预算"),
    ("actualExpense", "外部支出成本"),
    ("totalBudget", "项目总预算"),
    ("totalActualExpense", "动态总成本"),
    ("overBudget", "是否超预算"),
    ("permitNodes", "可用节点"),
    ("currentNode", "当前节点"),
    ("futurePlusSpent", "已支出与未来支出"),
    ("currentTotalPersonDay", "动态人日"),
    ("totalBudgetFromApproval", "预算审批合计金额"),
    ("actualTotalCost", "实际总成本"),
    ("finalPersonCost", "最终人日成本"),
    ("finalTotalCost", "最终总成本"),
    ("currentPersonCost", "实际人员成本"),
    ("pmoProductionCycleConfirmed", "PMO制作周期已确认"),
    ("pmoPersonCostAccountingCompleted", "PMO人员成本已核算"),
    ("pmoWorkflowNodeOrder", "PMO工作流节点顺序"),
    ("pmoLeftEstimatePersonDay", "PMO累计消耗人日"),
    ("averageDailyPersonDayConsumption", "日均消耗人日"),
    ("remainingPersonDay", "剩余人日"),
    ("remainingConsumableCalendarDays", "剩余人日可消耗天数"),
    ("dataRefreshedAt", "数据更新时间"),
    # 2.2 LarkProjectRevenueStats
    ("contractAmount", "合同金额"),
    ("revenueExcludingTax", "营收不含税金额"),
    ("revenueInvoiced", "营收已开票金额"),
    ("amountReceived", "回款含税金额"),
    ("amountReceivedExcludingTax", "回款不含税金额"),
    # 2.3 LarkProjectProfitData
    ("expectedGrossProfit", "预期毛利"),
    ("expectedGrossProfitRate", "预期毛利率"),
    ("expectedNetProfit", "预期净利"),
    ("expectedNetProfitRate", "预期净利率"),
    ("finalGrossProfit", "最终毛利"),
    ("finalGrossProfitRate", "最终毛利率"),
    ("finalNetProfit", "最终净利"),
    ("finalNetProfitRate", "最终净利率"),
    # 2.4 LarkProjectCost
    ("estimate", "预算"),
    ("actual", "实际支出"),
    # 2.5 LarkProjectBudgetDetail
    ("instanceCode", "审批实例ID"),
    ("serialNumber", "审批编号"),
    ("budgetDescription", "预算说明"),
    ("projectTotalRevenue", "项目总营收"),
    ("externalBudget", "外部支出预算"),
    ("personDayCostBudget", "人日成本预算"),
    ("projectTotalBudget", "项目总预算"),
    ("attachmentsJson", "附件JSON"),
    ("approvalEndAt", "审批完成时间"),
    # 2.6 LarkProjectExpenseDetail
    ("sourceType", "数据源类型"),
    ("lineIndex", "明细行序号"),
    ("feeType", "费用类型"),
    ("description", "费用说明"),
    ("payee", "付款对象"),
    ("relatedApproval", "关联审批"),
    ("amount", "金额"),
    # 2.7 LarkProjectContractDetail
    ("sealReason", "用印事由"),
    ("excludingTaxAmount", "不含税金额"),
    ("budgetRelatedApproval", "预算关联审批"),
    ("specialNote", "特殊说明"),
    # 2.8 LarkProjectReceiptRecord
    ("receiptAmount", "收款金额"),
    ("receiptPhase", "收款阶段"),
    ("receiptOccurredAt", "收款发生日期"),
    ("receiptEntity", "收款主体"),
    ("customerName", "客户名称"),
    # 2.9 LarkProjectExpenseApprovalSummary
    ("hoverFieldsJson", "hover字段JSON"),
    # 2.10 LarkProjectBudgetApproval
    ("approvalCode", "审批Code"),
    ("userId", "用户ID"),
    ("userName", "用户名称"),
    ("totalAmount", "金额总计"),
    ("endAt", "审批完成时间"),
    ("paymentDetailsJson", "付款明细JSON"),
    ("formData", "表单原始数据"),
    ("invoiceExcludingTaxAmount", "开票不含税金额"),
    # 2.11 LarkProjectExpectedNetProfitRateHistory
    ("sequence", "历史序号"),
    ("triggerInstanceCode", "触发审批实例ID"),
    ("recordedAt", "记录时间"),
    # 2.12 LarkProjectPersonDurationDetails
    ("userKey", "用户key"),
    ("role", "角色"),
    ("employeeType", "员工类型"),
    ("actualDefaulted", "实际是否默认值"),
    ("estimateDefaulted", "预计是否默认值"),
    ("current", "当前人日"),
    ("currentDefaulted", "当前人日是否默认"),
    # 2.13 LarkProjectNodeDetail
    ("stateKey", "节点key"),
    ("actualStartDate", "节点实际开始时间"),
    ("actualEndDate", "节点实际结束时间"),
    ("owners", "节点负责人"),
    ("estimateStartDate", "预计开始时间"),
    ("estimateEndDate", "预计结束时间"),
    ("estimatePoints", "预计天数"),
    ("actualPoints", "实际天数"),
    ("estimateDays", "预计天数"),
    ("actualDays", "实际天数"),
    # 2.14 LarkProjectNodePersonSchedule
    ("nodeId", "节点id"),
    ("nodeName", "节点名称"),
    ("estimatePersonDay", "预计人日"),
    ("actualPersonDay", "最终人日"),
    # 2.15 LarkProjectDelayDetail
    ("delayTime", "延期时间"),
    ("delayReason", "延期原因"),
    # 2.16 LarkProjectLeaveRecord
    ("unionId", "用户unionId"),
    ("endTime", "结束时间"),
    ("duration", "时长"),
    ("leaveType", "请假类型"),
    # 2.17 LarkProjectOvertimeRecord
    ("projectId", "飞书项目ID"),
    # 2.18 LarkProjectInfo
    ("domain", "空间域名"),
    # 2.19 LarkProjectUserInfo
    ("email", "用户邮箱"),
    ("nameCn", "用户中文名"),
    ("nameEn", "用户英文名"),
    ("avatar", "用户头像"),
    ("globalId", "全局ID"),
    ("departmentName", "部门名称"),
    ("rootDepartmentName", "根部门名称"),
    ("jobTitle", "岗位"),
    ("employeeNo", "员工工号"),
    # 2.20 LarkProjectAdmin
    ("phoneNumber", "用户手机号"),
    ("password", "密码"),
    # 2.21 ManualEdit
    ("fieldName", "字段名"),
    ("edited", "是否手动修改"),
    ("oldValue", "旧值"),
    ("newValue", "新值"),
    ("operator", "操作人"),
    ("operatedAt", "操作时间"),
    # 2.22 Notice
    ("noticeType", "通知类型"),
    ("content", "消息内容"),
    ("itemId", "工作项主键"),
    ("noticeTime", "通知时间"),
    ("noticeId", "消息ID"),
    ("adminId", "管理员ID"),
    ("bizKey", "防重业务键"),
    # 2.23 DashboardStats / PersonStatus
    ("statDate", "统计日期"),
    ("statType", "统计类型"),
    ("statsJson", "统计数据JSON"),
    ("idleStatus", "空转状态"),
    ("statusDescription", "状态描述"),
    ("relatedWorkItemId", "关联项目ID"),
    ("relatedProjectName", "关联项目名称"),
    ("days", "天数"),
    # 2.24 Snapshot
    ("startDate", "开始时间"),
    ("endDate", "结束时间"),
    ("personDay", "人日"),
    # 2.25 ProductionCycleConfirmSnapshot
    ("personEstimatesJson", "成员预计人日JSON"),
    ("nodeSchedulesJson", "节点预计排期JSON"),
    # 2.26 CalendarLinker
    ("workItemTypeName", "工作项类型名称"),
    ("workItemName", "项目名称"),
    ("plannedEndDate", "节点计划完成时间"),
    ("calendarId", "日历ID"),
    ("eventId", "日程ID"),
    # 2.27 LarkApproval
    ("approvalName", "审批名称"),
    ("approvalId", "审批ID"),
    ("uid", "UID"),
    ("openId", "OpenID"),
    ("departmentId", "部门ID"),
    ("rootDepartmentId", "根部门ID"),
    ("companyName", "公司名称"),
    ("pushState", "推送状态"),
    ("pushReason", "推送原因"),
    ("extra", "其他信息"),
    # 2.28 FenbeitongBillSyncLog
    ("billCode", "分贝通账单编号"),
    ("billStartMonth", "账单开始月份"),
    ("billEndMonth", "账单结束月份"),
    ("billCycle", "账单周期"),
    ("billState", "账单状态"),
    ("companyTotalPrice", "企业支付总金额"),
    ("billSummaryPdfUrl", "PDF账单URL"),
    ("syncStatus", "同步状态"),
    ("detailTotalCount", "明细总行数"),
    ("syncedRowCount", "已同步行数"),
    ("syncedAt", "同步时间"),
    ("errorMessage", "失败原因"),
    # 2.29 FenbeitongBillDetail
    ("orderCategory", "场景码"),
    ("categoryLabel", "场景标签"),
    ("orderId", "订单号"),
    ("ticketId", "票ID"),
    ("rootOrderId", "主订单号"),
    ("relationTicketId", "关联订单号"),
    ("orderCreateTime", "下单时间"),
    ("orderState", "订单状态"),
    ("orderCategoryType", "机票分类"),
    ("payerName", "预订人"),
    ("payerDept", "预订人部门"),
    ("tripInfo", "行程"),
    ("tripName", "酒店或商家名"),
    ("seatType", "舱位等级"),
    ("startCityName", "出发城市"),
    ("endCityName", "到达城市"),
    ("goodsNumber", "间夜数"),
    ("reason", "事由"),
    ("projectCode", "项目编号"),
    # 2.30 FenbeitongPushRecord
    ("scheduledPushAt", "计划推送时间"),
    ("pushed", "是否已推送"),
    ("created", "是否已创建项目"),
    ("pushedAt", "实际推送时间"),
    ("pushedStatus", "推送时飞书状态"),
    ("pushMessage", "推送结果消息"),
    ("pushRequest", "推送请求JSON"),
    ("pushResponse", "推送响应JSON"),
    # 2.31 Configuration
    ("key", "配置项"),
    ("value", "配置项值"),
    # 2.32 NasFileMeta
    ("path", "文件路径"),
    ("pathHash", "路径哈希"),
    ("length", "内容长度"),
    ("md5", "MD5"),
    ("sha256", "SHA256"),
    ("creationTime", "创建时间"),
    ("lastModifiedTime", "最后修改时间"),
    ("lastAccessTime", "最后访问时间"),
    ("fileType", "文件格式"),
    ("resolution", "分辨率"),
    ("codec", "编码"),
    ("frameRate", "帧率"),
    ("recordingAt", "拍摄时间"),
    ("fnumber", "光圈"),
    ("meta", "元数据"),
    # 2.33 NasTranscodingRecord
    ("sourceSha256", "源文件SHA256"),
    ("sourcePath", "源文件路径"),
    ("productFileName", "产品文件名"),
    ("mediaType", "媒体类型"),
    ("outputPath", "输出文件路径"),
    ("coverPath", "封面路径"),
    ("retryCount", "重试次数"),
    # 3.1 项目列表 VO
    ("excludePersonCostB", "外部支出预算"),
    ("totalB", "项目总预算"),
    ("totalAE", "动态总成本"),
    ("excludePersonCostAE", "外部支出成本"),
    ("currentGrossProfit", "实际毛利"),
    ("currentGrossProfitRate", "实际毛利率"),
    ("currentNetProfit", "实际净利"),
    ("currentNetProfitRate", "实际净利率"),
    ("profitActualGrossProfit", "最终毛利"),
    ("profitActualGrossProfitRate", "最终毛利率"),
    ("profitActualNetProfit", "最终净利"),
    ("profitActualNetProfitRate", "最终净利率"),
    ("currentTotalPersonDays", "动态人日"),
    ("currentNonPersonCost", "当前外部支出"),
    ("currentTotalCost", "动态总成本"),
    ("budgetProgress", "预算进度"),
    ("publishOverdueStatus", "发布逾期情况"),
    ("timeProgress", "时间进度"),
    ("manualEditFlags", "手动修改字段"),
    ("hasManualEdit", "是否存在手改"),
    ("role1", "商务负责人"),
    ("role2", "制片负责人"),
    ("role3", "影像编辑"),
    ("role4", "运营"),
    ("statistics", "支出项统计"),
    ("workItemPersons", "项目人员信息"),
    ("nodes", "项目节点信息"),
    ("currentPersonDay", "每人当前人日"),
    ("actualBeginTime", "节点实际开始时间"),
    ("actualFinishTime", "节点实际结束时间"),
    ("costDetail", "支出项详情"),
    ("expenseTotal", "支出金额合计"),
    ("items", "明细列表"),
    ("attachments", "附件列表"),
    ("budgetTotal", "预算金额合计"),
    ("contractTotal", "合同金额合计"),
    ("receiptTotal", "回款金额合计"),
    ("hoverFields", "hover展示字段"),
    ("label", "展示标签"),
    ("url", "附件下载URL"),
    # 3.7 DashboardVo
    ("overdueProjectCount", "逾期项目数"),
    ("completedProjectCount", "已完成项目数"),
    ("personIdleRate", "人员空转率"),
    ("inProgressProjectCount", "进行中项目数"),
    ("weeklyNewProjectCount", "每周新增项目数"),
    ("totalExpense", "项目总支出"),
    ("budgetExpenseRate", "预算支出比例"),
    ("totalRevenue", "项目营收"),
    ("totalContractRevenue", "合同营收"),
    ("totalExcludingTaxRevenue", "不含税营收"),
    ("avatarUrl", "头像URL"),
    ("statusPriority", "状态优先级"),
    ("owners", "负责人列表"),
    ("totalCost", "总成本"),
    ("costBudgetRate", "成本预算比例"),
    ("netProfitRevenueRate", "净利营收比例"),
    ("expectedNetProfitRateSequence", "净利率历史序号"),
    ("actualPersonDays", "实际人日总和"),
    ("expectedPersonDays", "预计人日总和"),
    ("personDayRate", "人日比例"),
    ("remainingPersonDayManuallyEdited", "剩余人日是否手改"),
    ("inProjectCount", "项目中人数"),
    ("idleSoonCount", "即将空转人数"),
    ("joinSoonCount", "即将进组人数"),
    ("noProjectCount", "无项目人数"),
    ("overdueDays", "逾期天数"),
    ("overdueStatus", "发布逾期状态"),
    ("rootDepartment", "一级部门"),
    ("subDepartments", "二级部门列表"),
    ("currentProjects", "当前进行中项目"),
    ("currentStatus", "人员当前状态"),
    ("personProjectStatus", "人员项目状态"),
    ("joinDate", "进组时间"),
    ("leaveDate", "出组时间"),
    # 3.8 EmployeeCalendarVo
    ("eventType", "事件类型"),
    ("isToday", "是否今天"),
    ("isCurrentMonth", "是否当前月"),
    ("dayOfWeek", "星期几"),
    ("events", "事件列表"),
    ("year", "年份"),
    ("month", "月份"),
    ("dates", "日期列表"),
    ("rows", "时间轴行列表"),
    # 3.9 NoticeVo
    ("isRead", "是否已读"),
    ("unreadCount", "未读消息数"),
    # 3.11 FenbeitongBillVo
    ("success", "是否成功"),
    ("requestedMonths", "请求月份列表"),
    ("defaultApplied", "是否默认月份"),
    ("defaultReason", "默认说明"),
    ("billCount", "账单数"),
    ("syncedBillCount", "同步成功账单数"),
    ("skippedBillCount", "跳过数"),
    ("totalDetailRows", "明细总行数"),
    ("failures", "失败列表"),
    ("message", "提示信息"),
    ("error", "失败原因"),
    ("page", "页码"),
    ("pageSize", "每页大小"),
    ("total", "总条数"),
    # 3.12 辅助 VO
    ("point", "估分"),
    ("owner", "负责人"),
    # 4.x Param
    ("itemType", "项目类型"),
    ("personBudgetBase", "人员预算基数"),
    ("EditItem", "编辑项"),
    ("departments", "部门筛选"),
    ("statuses", "状态筛选"),
    ("projectStatuses", "项目状态筛选"),
    ("noticeTimeStart", "通知开始时间"),
    ("noticeTimeEnd", "通知结束时间"),
    ("readStatus", "已读状态"),
    ("size", "每页数量"),
    ("publishYears", "发布年份筛选"),
    ("startYears", "开始年份筛选"),
    # 5.x 枚举（作为字段值列名时可能遇到）
    ("OVERDUE", "已逾期"),
    ("WARNING", "预警"),
    ("OVERDUE_PUBLISHED", "逾期发布"),
    ("NO_OVERDUE", "无逾期"),
    ("NO_PROJECT", "无项目"),
    ("IDLE_SOON", "即将空转"),
    ("JOIN_SOON", "即将进组"),
    ("IN_PROJECT", "项目中"),
    ("PERSON_DAY_WARNING", "人日消耗预警"),
    ("PERSON_IDLE", "人员空转通知"),
    ("PERSON_IDLE_WARNING", "人员空转预警"),
    ("PUBLISH_TIME_CHANGE", "发布时间修改"),
    ("OVERDUE_WARNING", "项目逾期预警"),
    ("COST_WARNING", "总成本消耗预警"),
    ("NET_PROFIT_RATE_WARNING", "净利率预警"),
    ("TOP_METRICS", "顶部统计指标"),
    ("PROJECT_COST_RISK", "项目成本风险"),
    ("PERSON_DAY_RISK", "人日成本风险"),
    ("DEPT_IDLE_STATS", "部门空转统计"),
    ("PROJECT_PUBLISH_RISK", "项目发布预警"),
    ("ESTIMATE", "预计"),
    ("ACTUAL", "最终"),
    ("CURRENT", "当前"),
    ("DEEP_VIDEO", "深度视频类"),
    ("TVC", "TVC类"),
    ("IMAGE_TEXT", "图文项目类"),
    ("UNAVAILABLE", "待审批"),
    ("SHOULD_CONFIRM", "待手动确认"),
    ("SHOULD_PUSH", "待推送"),
    ("PUSHED", "已推送"),
    ("FAILED", "推送失败"),
    ("LEAVE", "请假"),
    ("OVERTIME", "加班"),
    # 6.x 财务凭证
    ("cid", "申请编号"),
    ("cbillcode", "单据编码"),
    ("cztid", "公司编号"),
    ("dbilldate", "单据日期"),
    ("cmemo", "摘要"),
    ("irows", "明细行数"),
    ("cpzlb", "凭证类别"),
    ("mje", "借方金额合计"),
    ("idoc", "附单据数"),
    ("cbill", "制单人"),
    ("quickly", "快速凭证"),
    ("cdigest", "摘要"),
    ("cfx", "方向"),
    ("ccode", "科目编号"),
    ("cdepname", "部门名称"),
    ("cpername", "人员名称"),
    ("cdwname", "单位名称"),
    ("cxmid", "项目ID"),
    ("capixmname", "项目名称"),
    ("cxjllcode", "现金流量编码"),
    # 7.x Controller 参数
    ("yearMonth", "单月"),
    ("startMonth", "区间起始月"),
    ("endMonth", "区间结束月"),
    ("force", "是否强制重拉"),
    ("presetType", "人日类型"),
    ("keyword", "关键词"),
    # 预算审批 snake_case 别名（JSON 常见）
    ("project_name", "项目名称"),
    ("work_item_name", "项目名称"),
    ("work_item_id", "工作项ID"),
    ("created_at", "创建时间"),
    ("updated_at", "更新时间"),
    ("approval_end_at", "审批完成时间"),
    ("person_day_cost_budget", "人日成本预算"),
]
